{% set version = "0.1.0" %}

package:
  name: tegenomesimulator
  version: {{ version }}

source:
  path: ./TEgenomeSimulator

build:
  noarch: python
  script: python setup.py install
  #script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python #>=3.9
    - biopython #=1.81
    - pyyaml #=6.0.1
    - numpy #=1.26.2
    - pandas #=2.2.1

test:
  imports:
    - tegenomesimulator

about:
  home: https://github.com/PlantandFoodResearch/TEgenomeSimulator
  license: MIT
  summary: 'A tool to simulate TE mutation and insertion into a random-synthesised or user-provided genome'
