{% set version = "0.1.0" %}

package:
  name: tegenomesimulator
  version: {{ version }}

source:
  path: ./TEgenomeSimulator

build:
  noarch: python
  script: python setup.py install
  #script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python #>=3.9
    - biopython #=1.81
    - pyyaml #=6.0.1
    - numpy #=1.26.2
    - pandas #=2.2.1

test:
  imports:
    - tegenomesimulator

about:
  home: https://github.com/PlantandFoodResearch/TEgenomeSimulator
  license: MIT
  summary: 'A tool to simulate TE mutation and insertion into a random-synthesised or user-provided genome'

#package:
#  name: tegenomesimulator
#  version: "0.1.0"
#
#source:
#  path: .  # Path to the source code directory (TEgnomeSimulator)
#
#build:
#  noarch: python  # This indicates the package is architecture-independent (pure Python)
#  script: python setup.py install  # Custom build steps (can use setup.py)
#
#requirements:
#  build:
#    - python >=3.9
#    - setuptools
#  run:
#    - python >=3.9
#    - biopython =1.81
#    - pyyaml =6.0.1
#    - numpy =1.26.2
#    - pandas =2.2.1
#
#test:
#  imports:
#    - TEgenomeSimulator  # Check if we can import the main tool package
#  commands:
#    - python -c "import TEgenomeSimulator; print(TEgenomeSimulator.__version__))"  # Test a function in your main module
#    - python -c "from TEgenomeSimulator.utils import prep_sim_TE_lib"  # Test importing a subprocess script
#    - python -c "from TEgenomeSimulator.utils import prep_yml_config"  # Test importing a subprocess script
#    - python -c "from TEgenomeSimulator.utils import TE_sim_random_insertion"  # Test importing a subprocess script
#    - python -c "from TEgenomeSimulator.utils import TE_sim_nested_insertion"  # Test importing a subprocess script
#
#
#about:
#  home: https://github.com/PlantandFoodResearch/TEgenomeSimulator
#  license: MIT
#  summary: "TEgenomeSimulator: A tool to simulate TE mutation and insertion into a random-synthesised or user-provided genome."
#
#extra:
#  recipe-maintainers:
#    - ting-hsuan-chen