name: Build

on:
  release:
    types:
      - published
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker push
        run: |
          export APP_NAME=tegenomesimulator
          export APP_VERSION=$(grep version setup.py | sed -E "s/.*version=['\"]([^'\"]+)['\"].*/\1/")

          docker build -t ${APP_NAME}:${APP_VERSION} 
          docker tag ${APP_NAME}:${APP_VERSION} ghcr.io/plant-food-research-open/${APP_NAME}:${APP_VERSION}
          docker tag ${APP_NAME}:${APP_VERSION} ghcr.io/plant-food-research-open/${APP_NAME}:latest
          
          docker push ghcr.io/plant-food-research-open/${APP_NAME}:${APP_VERSION}
          docker push ghcr.io/plant-food-research-open/${APP_NAME}:latest

